import { NextRequest, NextResponse } from "next/server";
import { authClient } from "@/server/supabase";
import { requiredEnv } from "@/server/config";
// One-time invite/recovery links generated by trusted administration tooling.
export async function GET(req: NextRequest) {
  const token_hash = req.nextUrl.searchParams.get("token_hash");
  const type = req.nextUrl.searchParams.get("type");
  const origin = requiredEnv("SITE_URL");
  if (token_hash && (type === "invite" || type === "recovery")) {
    const supabase = await authClient();
    const { error } = await supabase.auth.verifyOtp({ token_hash, type });
    if (!error)
      return NextResponse.redirect(new URL("/reset-password", origin), {
        headers: {
          "Cache-Control": "no-store",
          "Referrer-Policy": "no-referrer",
        },
      });
  }
  return NextResponse.redirect(new URL("/auth/error", origin));
}
